const cityName = [
    "Amsterdam",
    "Berlin",
    "London",
    "New York",
    "Paris",
    "Rome",
    "San Francisco",
    "Tokyo",
    "Washington DC",
    "Zurich",
    "Copenhagen",
    "Helsinki",
    "Madrid",
    "Reykjavik",
    "Stockholm",
    "Vancouver",
    "Vienna",
    "Zagreb",
    "Budapest",
    "Dublin",
    "Hamburg",
    "Krakow",
    "Lisbon",
    "Johhanesberg",
    "New Delhi",
    "Mumbai",
    "Bengaluru",
    "Kolkata",
    "Chennai",
    "Bejieng",
    "Kualalumpur",
    "Sydney",
    "Melbourne",
    "Manchester",
    "Dubai",
    "Abu Dhabi",
    "Moscow",
    "Tel Aviv",
    "Auckland",
    "Brisbane",
    "Rio De Jenerio",
    "Peru",
    "Cape Town",
    "Seol"
];

export default cityName;
